% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Tarea 2 de la semana 3 Python},
  pdfauthor={Geovanna Gonzalez},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Tarea 2 de la semana 3 Python}
\author{Geovanna Gonzalez}
\date{2023-10-10}

\begin{document}
\maketitle

La integración de Python en RStudio se logra mediante la instalación de
paquetes como ``reticulate'', que facilita la ejecución de código Python
en un entorno de RStudio. Esta combinación de lenguajes ofrece un
entorno completo y versátil para proyectos de análisis de datos y
científicos que requieren el uso de ambas plataformas.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(reticulate)}
\end{Highlighting}
\end{Shaded}

\hypertarget{paquetes-a-utilizar}{%
\subsection{Paquetes a utilizar}\label{paquetes-a-utilizar}}

El paquete \textbf{os} se usa para tareas como la navegación por el
sistema de archivos, la creación de directorios, la verificación de la
existencia de archivos y más.

\begin{Shaded}
\begin{Highlighting}[]
\ImportTok{import}\NormalTok{ os}
\end{Highlighting}
\end{Shaded}

El paquete \textbf{glob} se utiliza principalmente para buscar y listar
archivos en un directorio que cumplan con ciertos criterios de nombre.

\begin{Shaded}
\begin{Highlighting}[]
\ImportTok{import}\NormalTok{ glob}
\end{Highlighting}
\end{Shaded}

\textbf{Pandas} se utiliza ampliamente para cargar, limpiar, transformar
y analizar datos tabulares, como hojas de cálculo o conjuntos de datos
en formato CSV o Excel.

\begin{Shaded}
\begin{Highlighting}[]
\ImportTok{import}\NormalTok{ pandas }\ImportTok{as}\NormalTok{ pd}
\end{Highlighting}
\end{Shaded}

\textbf{NumPy} es esencial para la manipulación de datos numéricos,
cálculos matemáticos y estadísticos, y es ampliamente utilizado en áreas
como la ciencia de datos, la ingeniería y la investigación científica.

\begin{Shaded}
\begin{Highlighting}[]
\ImportTok{import}\NormalTok{ numpy }\ImportTok{as}\NormalTok{ np}
\end{Highlighting}
\end{Shaded}

\textbf{Matplotlib} se utiliza para visualizar datos y resultados en
forma de gráficos. Puede generar gráficos personalizados para explorar y
comunicar información de manera efectiva.

\begin{Shaded}
\begin{Highlighting}[]
\ImportTok{import}\NormalTok{ matplotlib.pyplot }\ImportTok{as}\NormalTok{ plt}
\end{Highlighting}
\end{Shaded}

Una vez importados los paquetes a utilizar, se puede acceder al url,
empleando la función read\_csv() para la lectura de un archivo que se
encuentra alojado en una página web. En esta situación, simplemente se
proporciona la dirección web entre comillas como parte de los parámetros
de la función.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{datos\_feli }\OperatorTok{=}\NormalTok{ pd.read\_csv(}\StringTok{\textquotesingle{}https://raw.githubusercontent.com/cienciadedatos/datos{-}de{-}miercoles/master/datos/2019/2019{-}08{-}07/felicidad.csv\textquotesingle{}}\NormalTok{)}
\NormalTok{datos\_feli}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##              pais  anio  ...  gini_banco_mundial  gini_banco_mundial_promedio
## 0     Afghanistán  2008  ...                 NaN                          NaN
## 1     Afghanistán  2009  ...                 NaN                          NaN
## 2     Afghanistán  2010  ...                 NaN                          NaN
## 3     Afghanistán  2011  ...                 NaN                          NaN
## 4     Afghanistán  2012  ...                 NaN                          NaN
## ...           ...   ...  ...                 ...                          ...
## 1699     Zimbabue  2014  ...                 NaN                        0.432
## 1700     Zimbabue  2015  ...                 NaN                        0.432
## 1701     Zimbabue  2016  ...                 NaN                        0.432
## 1702     Zimbabue  2017  ...                 NaN                        0.432
## 1703     Zimbabue  2018  ...                 NaN                        0.432
## 
## [1704 rows x 17 columns]
\end{verbatim}

Para este ejercicio se utilizará solo ciertas variables las 7 primeras.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\OperatorTok{=}\NormalTok{ datos\_feli.iloc[:, }\DecValTok{0}\NormalTok{:}\DecValTok{7}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

Se filtra el conjunto de datos para seleccionar los datos
correspondientes al primer año y al último año.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{primer\_anio }\OperatorTok{=}\NormalTok{ datos\_feli[datos\_feli[}\StringTok{\textquotesingle{}anio\textquotesingle{}}\NormalTok{] }\OperatorTok{==}\NormalTok{ datos\_feli[}\StringTok{\textquotesingle{}anio\textquotesingle{}}\NormalTok{].}\BuiltInTok{min}\NormalTok{()]}
\NormalTok{ultimo\_anio }\OperatorTok{=}\NormalTok{ datos\_feli[datos\_feli[}\StringTok{\textquotesingle{}anio\textquotesingle{}}\NormalTok{] }\OperatorTok{==}\NormalTok{ datos\_feli[}\StringTok{\textquotesingle{}anio\textquotesingle{}}\NormalTok{].}\BuiltInTok{max}\NormalTok{()]}
\end{Highlighting}
\end{Shaded}

Medida de tendencia central y la dispersión para ambas selecciones

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{media\_primer\_anio }\OperatorTok{=}\NormalTok{ primer\_anio[}\StringTok{\textquotesingle{}escalera\_vida\textquotesingle{}}\NormalTok{].mean()}
\NormalTok{desviacion\_primer\_anio }\OperatorTok{=}\NormalTok{ primer\_anio[}\StringTok{\textquotesingle{}escalera\_vida\textquotesingle{}}\NormalTok{].std()}
\end{Highlighting}
\end{Shaded}

Para el primer año:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{media\_primer\_anio }\OperatorTok{=}\NormalTok{ primer\_anio[}\StringTok{\textquotesingle{}escalera\_vida\textquotesingle{}}\NormalTok{].mean()}
\BuiltInTok{print}\NormalTok{(media\_primer\_anio )}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 6.446164272449635
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{desviacion\_primer\_anio }\OperatorTok{=}\NormalTok{ primer\_anio[}\StringTok{\textquotesingle{}escalera\_vida\textquotesingle{}}\NormalTok{].std()}
\BuiltInTok{print}\NormalTok{(desviacion\_primer\_anio)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 0.9191426322726483
\end{verbatim}

Para el último año:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{media\_ultimo\_anio }\OperatorTok{=}\NormalTok{ ultimo\_anio[}\StringTok{\textquotesingle{}escalera\_vida\textquotesingle{}}\NormalTok{].mean()}
\BuiltInTok{print}\NormalTok{(media\_ultimo\_anio )}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 5.502134340650895
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{desviacion\_ultimo\_anio }\OperatorTok{=}\NormalTok{ ultimo\_anio[}\StringTok{\textquotesingle{}escalera\_vida\textquotesingle{}}\NormalTok{].std()}
\BuiltInTok{print}\NormalTok{(desviacion\_ultimo\_anio)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 1.1034612436939357
\end{verbatim}

o de ser el caso con un \textbf{describe()}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data.describe()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##               anio  escalera_vida  ...  expectativa_vida     libertad
## count  1704.000000    1704.000000  ...       1676.000000  1675.000000
## mean   2012.332160       5.437155  ...         63.111971     0.733829
## std       3.688072       1.121149  ...          7.583622     0.144115
## min    2005.000000       2.661718  ...         32.299999     0.257534
## 25%    2009.000000       4.610970  ...         58.299999     0.638436
## 50%    2012.000000       5.339557  ...         65.000000     0.752731
## 75%    2015.000000       6.273522  ...         68.300003     0.848155
## max    2018.000000       8.018934  ...         76.800003     0.985178
## 
## [8 rows x 6 columns]
\end{verbatim}

En este caso, se analizará para 2 países de Sudamérica. Se procede a
seleccionar Ecuador y Colombia para realizar un análisis comparativo :

\begin{Shaded}
\begin{Highlighting}[]

\NormalTok{paises\_especificos }\OperatorTok{=}\NormalTok{ [}\StringTok{\textquotesingle{}Ecuador\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}Colombia\textquotesingle{}}\NormalTok{]}
\CommentTok{\# Filtrar la columna \textquotesingle{}Country\textquotesingle{} para mantener solo los países específicos}
\NormalTok{data[}\StringTok{\textquotesingle{}pais\textquotesingle{}}\NormalTok{] }\OperatorTok{=}\NormalTok{ data[}\StringTok{\textquotesingle{}pais\textquotesingle{}}\NormalTok{].}\BuiltInTok{apply}\NormalTok{(}\KeywordTok{lambda}\NormalTok{ x: x }\ControlFlowTok{if}\NormalTok{ x }\KeywordTok{in}\NormalTok{ paises\_especificos }\ControlFlowTok{else} \StringTok{\textquotesingle{}\textquotesingle{}}\NormalTok{)}

\CommentTok{\# Crear un nuevo DataFrame solo con los países específicos}
\NormalTok{datact }\OperatorTok{=}\NormalTok{ data[data[}\StringTok{\textquotesingle{}pais\textquotesingle{}}\NormalTok{].isin(paises\_especificos)]}
\end{Highlighting}
\end{Shaded}

Obtener el primer año y el último:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Obtener el primer año (mínimo) y el último año (máximo) en el DataFrame}
\NormalTok{primer\_anio }\OperatorTok{=}\NormalTok{ datact[}\StringTok{\textquotesingle{}anio\textquotesingle{}}\NormalTok{].}\BuiltInTok{min}\NormalTok{()}
\NormalTok{ultimo\_anio }\OperatorTok{=}\NormalTok{ datact[}\StringTok{\textquotesingle{}anio\textquotesingle{}}\NormalTok{].}\BuiltInTok{max}\NormalTok{()}

\CommentTok{\# Filtrar los datos para el primer y último año}
\NormalTok{datos\_primer\_anios }\OperatorTok{=}\NormalTok{ datact[datact[}\StringTok{\textquotesingle{}anio\textquotesingle{}}\NormalTok{] }\OperatorTok{==}\NormalTok{ primer\_anio]}
\BuiltInTok{print}\NormalTok{(datos\_primer\_anios)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          pais  anio  escalera_vida  ...  soporte_social  expectativa_vida  libertad
## 315  Colombia  2006       6.024943  ...        0.910293         65.220001  0.804662
## 427   Ecuador  2006       5.024191  ...        0.910188         66.080002  0.671075
## 
## [2 rows x 7 columns]
\end{verbatim}

En 2006, Colombia mostraba una puntuación de ``escalera\_vida'' de
alrededor de 6.025, mientras que Ecuador tenía una calificación de
aproximadamente 5.024. Esto sugiere que, en ese año en particular, la
percepción de la calidad de vida o la felicidad en Colombia superaba a
la de Ecuador. Sin embargo, al comparar estos valores con la media
global de \textbf{6.446164272449635}, se observa que Colombia se acerca
más a esta media, con una diferencia de aproximadamente 0.42 puntos. En
contraste, Ecuador se encuentra a más de una unidad por debajo de la
media global en esta métrica. Esta comparación subraya las diferencias
significativas en la percepción de la calidad de vida entre ambos países
en ese período.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{datos\_ultimo\_anios }\OperatorTok{=}\NormalTok{ datact[datact[}\StringTok{\textquotesingle{}anio\textquotesingle{}}\NormalTok{] }\OperatorTok{==}\NormalTok{ ultimo\_anio]}
\BuiltInTok{print}\NormalTok{(datos\_ultimo\_anios)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          pais  anio  escalera_vida  ...  soporte_social  expectativa_vida  libertad
## 327  Colombia  2018       5.983512  ...        0.870970         67.699997  0.850766
## 439   Ecuador  2018       6.128010  ...        0.851345         68.500000  0.869364
## 
## [2 rows x 7 columns]
\end{verbatim}

En 2018, Ecuador tenía una puntuación más alta en la ``escalera\_vida''
(6.128010) en comparación con Colombia (5.983512). Esto sugiere que,
según la percepción de las personas, la calidad de vida y la felicidad
eran ligeramente mejores en Ecuador en ese año.De la misma forma si se
compara a nive global en el ùltimo año \textbf{5.502134340650895} se
observa que Ecuador en 2018 superó la media global. Ecuador también
tiene un valor ligeramente más alto en la métrica de ``soporte\_social''
(0.851345) en comparación con Colombia (0.870970). Esto indica que, en
términos de la percepción de apoyo social, Ecuador tenía una ligera
ventaja en 2018.Además, la expectativa de vida ligeramente mayor (68.5
años) en comparación con Colombia (67.7 años). Esto sugiere que, en
promedio, las personas en Ecuador podían esperar vivir un poco más que
las personas en Colombia en ese año.De igual forma ``libertad'' mostró
una ligera ventaja para Ecuador (0.869364) en comparación con Colombia
(0.850766) en 2018, lo que indica que las personas en Ecuador percibían
una mayor libertad en sus vidas.

En resumen, según estos datos, en 2018, Ecuador tenía una percepción
ligeramente mejor de la calidad de vida y la felicidad en comparación
con Colombia. Además, Ecuador también tenía valores ligeramente más
altos en las métricas de soporte social, expectativa de vida y libertad,
posiblemente estos factores expliquen porque Ecuador tiene un mayor
nivel de felicidad. Sin embargo, para un análisis riguroso es
recomendables utilizar un modelo econométrico.

\end{document}
